import { TriggerContext } from '../types';
import { log } from '../utils/logger';
import { runEnrichmentAgent } from '../agents/enrichmentAgent';
import { getIssue, commentOnIssue, transitionToInQA } from '../services/issues';
import { getKeywordMap } from '../services/testRepo';
import { detectFeature } from '../utils/featureDetector';
import { fetchPRDiff } from '../utils/diffAnalyzer';
import {
  findPRByTicketId,
  findBranchesByPattern,
  openPR,
  commitFile,
  testRepoName,
  ownerName,
  mainRepo,
} from '../services/github';
import { toSpecFileName } from '../utils/naming';
import { pomPathFromContent } from '../agents/tools/outputTools';

export async function flow2(context: TriggerContext): Promise<void> {
  log('INFO', `[Flow 2] Starting for issue #${context.ticketId}`);

  const issue = context.issue ?? await getIssue(Number(context.ticketId));
  const keywordMap = await getKeywordMap().catch(() => ({} as Record<string, string[]>));
  const feature = detectFeature(issue.body, issue.labels, issue.title, keywordMap);

  // Find QA branch
  const branches = await findBranchesByPattern(testRepoName(), `qa/${context.ticketId}-`);
  if (branches.length === 0) {
    throw new Error(`[Flow 2] No QA branch found for ticket ${context.ticketId}`);
  }
  const branch = branches[0];
  log('INFO', `[Flow 2] Using branch: ${branch}`);

  // Fetch PR diff from dev repo (best-effort)
  let prDiff = '';
  const devPR = await findPRByTicketId(context.ticketId, mainRepo()).catch(() => null);
  if (devPR) {
    prDiff = await fetchPRDiff(devPR.number, ownerName(), mainRepo(), process.env.GITHUB_TOKEN ?? '');
    log('INFO', `[Flow 2] PR diff fetched (${prDiff.length} chars)`);
  }

  // Run enrichment agent (no crawling — snapshots passed as empty array until playwright/mcp lands)
  const result = await runEnrichmentAgent(issue, feature, branch, [], prDiff);
  const specContent = result.enrichedSpec;
  const pomContent = result.pomContent;
  const affectedPaths = result.affectedPaths;
  const tokenUsage = result.tokenUsage;
  let pomPath = `pages/${feature}/${feature.charAt(0).toUpperCase() + feature.slice(1)}Page.ts`;

  // Sanity-check: ensure pomPath matches the exported class name in the content
  const derivedPath = pomPathFromContent(pomContent, feature);
  if (pomPath !== derivedPath) {
    log('WARN', `[Flow 2] pomPath mismatch — agent said "${pomPath}", class name implies "${derivedPath}". Using derived path.`);
    pomPath = derivedPath;
  }

  // Commit enriched spec + POM
  const specPath = `tests/web/${feature}/${toSpecFileName(context.ticketId, issue.title)}`;

  await commitFile(
    testRepoName(), branch, specPath, specContent,
    `feat(spec): enrich #${context.ticketId} with real selectors [klikagent]`,
  );
  await commitFile(
    testRepoName(), branch, pomPath, pomContent,
    `feat(pom): add ${feature} POM for #${context.ticketId} [klikagent]`,
  );

  // Open PR in klikagent-tests
  const prUrl = await openPR(
    testRepoName(),
    branch,
    `[QA] #${context.ticketId} ${issue.title}`,
    `Automated test spec generated by KlikAgent.\n\nIssue: ${issue.url}\nFeature: \`${feature}\`\nAffected paths: \`${affectedPaths}\``,
  );

  // Transition labels + comment on issue
  await transitionToInQA(Number(context.ticketId));

  await commentOnIssue(
    Number(context.ticketId),
    `🤖 **KlikAgent** — Enriched spec ready for QA!\n\n` +
    `PR: ${prUrl}\n\n` +
    `Issue moved to \`status:in-qa\`. Tests will run automatically on the PR.\n\n` +
    `> Tokens: ${tokenUsage.promptTokens.toLocaleString()} prompt + ${tokenUsage.completionTokens.toLocaleString()} completion = **${tokenUsage.totalTokens.toLocaleString()} total**`,
  );

  log('INFO', `[Flow 2] Done — PR opened: ${prUrl}`);
}
