import { TriggerContext } from '../types';
import { log } from '../utils/logger';
import { runEnrichmentAgent } from '../agents/enrichmentAgent';
import { runReworkAgent } from '../agents/reworkAgent';
import { getIssue, commentOnIssue, transitionToInQA } from '../services/issues';
import { getRouteMap, getKeywordMap } from '../services/testRepo';
import { captureSnapshots } from '../services/crawler';
import { detectFeature } from '../utils/featureDetector';
import { resolveUrls } from '../utils/routeResolver';
import { fetchPRDiff } from '../utils/diffAnalyzer';
import {
  findPRByTicketId,
  findBranchesByPattern,
  openPR,
  commitFile,
  testRepoName,
  ownerName,
  mainRepo,
} from '../services/github';
import { toSpecFileName } from '../utils/naming';

const QA_BASE_URL = () => process.env.QA_BASE_URL ?? 'http://localhost:3000';

export async function flow2(context: TriggerContext): Promise<void> {
  log('INFO', `[Flow 2] Starting for issue #${context.ticketId}`);

  const issue = context.issue ?? await getIssue(Number(context.ticketId));
  const keywordMap = await getKeywordMap().catch(() => ({} as Record<string, string[]>));
  const feature = detectFeature(issue.body, issue.labels, issue.title, keywordMap);

  // Find QA branch created by flow1
  const branches = await findBranchesByPattern(testRepoName(), `qa/${context.ticketId}-`);
  if (branches.length === 0) {
    throw new Error(`[Flow 2] No QA branch found for ticket ${context.ticketId} — has Flow 1 run?`);
  }
  const branch = branches[0];
  log('INFO', `[Flow 2] Using branch: ${branch}`);

  // Fetch PR diff from dev repo (best-effort)
  let prDiff = '';
  const devPR = await findPRByTicketId(context.ticketId, mainRepo()).catch(() => null);
  if (devPR) {
    prDiff = await fetchPRDiff(devPR.number, ownerName(), mainRepo(), process.env.GITHUB_TOKEN ?? '');
    log('INFO', `[Flow 2] PR diff fetched (${prDiff.length} chars)`);
  }

  // Resolve URLs and crawl
  const routeMap = await getRouteMap().catch(() => ({} as Record<string, string>));
  const paths = resolveUrls(feature, issue.body, routeMap);
  const urls = paths.map((p) => `${QA_BASE_URL()}${p}`);

  if (urls.length === 0) {
    log('WARN', `[Flow 2] No URLs resolved for feature "${feature}" — crawling base URL`);
    urls.push(QA_BASE_URL());
  }

  log('INFO', `[Flow 2] Crawling ${urls.length} URL(s): ${urls.join(', ')}`);
  const snapshots = await captureSnapshots(urls);
  log('INFO', `[Flow 2] Captured ${snapshots.length} snapshot(s)`);

  // Run enrichment or rework agent
  let specContent: string;
  let pomContent: string;
  let affectedPaths = `tests/web/${feature}/`;

  let tokenUsage: import('../services/ai').TokenUsage;

  if (context.isRework && context.parentTicketId) {
    log('INFO', `[Flow 2] Rework mode — parentTicketId: ${context.parentTicketId}`);
    const parentIssue = await getIssue(Number(context.parentTicketId));
    const result = await runReworkAgent(issue, parentIssue, feature, branch, snapshots);
    specContent = result.patchedSpec;
    pomContent = result.pomContent;
    tokenUsage = result.tokenUsage;
  } else {
    const result = await runEnrichmentAgent(issue, feature, branch, snapshots, prDiff);
    specContent = result.enrichedSpec;
    pomContent = result.pomContent;
    affectedPaths = result.affectedPaths;
    tokenUsage = result.tokenUsage;
  }

  // Commit enriched spec + POM
  const specPath = `tests/web/${feature}/${toSpecFileName(context.ticketId, issue.title)}`;
  const pomPath = `pages/${feature}/${capitalize(feature)}Page.ts`;

  await commitFile(
    testRepoName(), branch, specPath, specContent,
    `feat(spec): enrich #${context.ticketId} with real selectors [klikagent]`,
  );
  await commitFile(
    testRepoName(), branch, pomPath, pomContent,
    `feat(pom): add ${feature} POM for #${context.ticketId} [klikagent]`,
  );

  // Open PR in klikagent-tests
  const prUrl = await openPR(
    testRepoName(),
    branch,
    `[QA] #${context.ticketId} ${issue.title}`,
    `Automated test spec generated by KlikAgent.\n\nIssue: ${issue.url}\nFeature: \`${feature}\`\nAffected paths: \`${affectedPaths}\``,
  );

  // Transition labels + comment on issue
  await transitionToInQA(Number(context.ticketId));

  await commentOnIssue(
    Number(context.ticketId),
    `🤖 **KlikAgent** — Enriched spec ready for QA!\n\n` +
    `PR: ${prUrl}\n` +
    `Crawled ${snapshots.length} page(s) from QA environment.\n\n` +
    `Issue moved to \`status:in-qa\`. Tests will run automatically on the PR.\n\n` +
    `> Tokens: ${tokenUsage.promptTokens.toLocaleString()} prompt + ${tokenUsage.completionTokens.toLocaleString()} completion = **${tokenUsage.totalTokens.toLocaleString()} total**`,
  );

  log('INFO', `[Flow 2] Done — PR opened: ${prUrl}`);
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
