import { QATask, GitHubIssue } from '../types';
import { log } from '../utils/logger';
import { commentOnIssue, transitionToInQA } from '../services/issues';
import { runWithSelfCorrection } from '../services/selfCorrection';
import {
  getDefaultBranchSha,
  createBranch,
  openPR,
  commitFile,
  testRepoName,
} from '../services/github';
import { toSpecFileName, toBranchSlug } from '../utils/naming';

export async function generateQaSpecFlow(task: QATask): Promise<void> {
  log('INFO', `[generateQaSpecFlow] Starting for task ${task.taskId}`);

  // Build a GitHubIssue-compatible object from QATask fields so downstream
  // services (qaAgent, selfCorrection) don't need to know about QATask yet.
  // TODO(Phase 3): replace with QATask directly once agents are refactored.
  const issue: GitHubIssue = {
    number: Number(task.taskId),
    title: task.title,
    body: task.description,
    url: (task.metadata?.issueUrl as string | undefined) ?? '',
    labels: [],
  };

  // TODO(Phase 3): feature, personas, startingUrls will be first-class QATask fields
  const feature = 'general';
  const personas: string[] = [];
  const startingUrls: string[] = [];
  const prDiff = '';

  // Create QA branch in the output repo
  const branch = toBranchSlug(task.taskId, task.title);
  const baseSha = await getDefaultBranchSha(task.outputRepo);
  await createBranch(task.outputRepo, branch, baseSha);
  log('INFO', `[generateQaSpecFlow] QA branch created: ${branch}`);

  // Derive spec path
  const specPath = `tests/web/${feature}/${toSpecFileName(task.taskId, task.title)}`;
  log('INFO', `[generateQaSpecFlow] Spec path: ${specPath}`);

  // Run self-correction loop (QA agent + tsc validation)
  const result = await runWithSelfCorrection(
    issue,
    feature,
    branch,
    personas,
    startingUrls,
    prDiff,
    specPath,
  );

  const { specContent, poms, affectedPaths, tokenUsage } = result;

  // Commit spec + POMs to branch
  await commitFile(
    task.outputRepo, branch, specPath, specContent,
    `feat(spec): add #${task.taskId} spec [klikagent]`,
  );
  for (const { pomContent, pomPath } of poms) {
    await commitFile(
      task.outputRepo, branch, pomPath, pomContent,
      `feat(pom): add ${feature} POM for #${task.taskId} [klikagent]`,
    );
  }

  // Open draft PR in output repo
  const prUrl = await openPR(
    task.outputRepo,
    branch,
    `[QA] #${task.taskId} ${task.title}`,
    `Automated QA spec generated by KlikAgent.\n\nTask: ${task.taskId}\nFeature: \`${feature}\`\nAffected paths: \`${affectedPaths}\``,
  );

  // Transition issue label + comment with result
  await transitionToInQA(issue.number);

  const warnBlock = result.warned
    ? `\n\n> ⚠️ **Warning:** ${result.warningMessage ?? 'Self-correction exhausted all attempts — spec may need manual review.'}`
    : '';

  await commentOnIssue(
    issue.number,
    `🤖 **KlikAgent** — QA spec generated!\n\n` +
    `PR: ${prUrl}\n\n` +
    `Issue moved to \`status:in-qa\`. Tests will run automatically on the PR.\n\n` +
    `> Tokens: ${tokenUsage.promptTokens.toLocaleString()} prompt + ${tokenUsage.completionTokens.toLocaleString()} completion = **${tokenUsage.totalTokens.toLocaleString()} total**` +
    warnBlock,
  );

  log('INFO', `[generateQaSpecFlow] Done — PR opened: ${prUrl}`);
}
