import { QATask, TaskResult } from '../types';
import { log } from '../utils/logger';
import { runWithSelfCorrection } from '../services/selfCorrection';
import { ensureRepo } from '../services/localRepo';
import {
  getDefaultBranchSha,
  createBranch,
  openPR,
  commitFile,
} from '../services/github';
import { toSpecFileName, toBranchSlug } from '../utils/naming';
import { dashboardBus } from '../dashboard/eventBus';

export async function generateQaSpecFlow(task: QATask): Promise<void> {
  log('INFO', `[generateQaSpecFlow] Starting for task ${task.taskId}${task.feature ? ` feature-hint=${task.feature}` : ''}`);

  // Phase 1: Ensure local clone is ready for fast reads and discovery tools
  await ensureRepo(task.outputRepo);

  // Create QA branch in the output repo
  const branch = toBranchSlug(task.taskId, task.title);
  const baseSha = await getDefaultBranchSha(task.outputRepo);
  await createBranch(task.outputRepo, branch, baseSha);
  log('INFO', `[generateQaSpecFlow] QA branch created: ${branch}`);
  dashboardBus.emitEvent('github', 'info', `QA branch created: ${branch}`, { branch, baseSha });

  // Run self-correction loop (QA agent + tsc validation)
  // The agent determines the feature from context; files are committed as-is
  const result = await runWithSelfCorrection(task, branch);
  const { feature, files, affectedPaths, tokenUsage } = result;

  log('INFO', `[generateQaSpecFlow] Agent determined feature=${feature}, files=${files.length}`);

  // Commit all generated files to branch
  for (const file of files) {
    await commitFile(
      task.outputRepo,
      branch,
      file.path,
      file.content,
      `feat(${file.role}): ${file.path} for #${task.taskId} [klikagent]`,
    );
    log('INFO', `[generateQaSpecFlow] Committed ${file.path}`);
  }

  // Open draft PR in output repo
  const prUrl = await openPR(
    task.outputRepo,
    branch,
    `[QA] #${task.taskId} ${task.title}`,
    `Automated QA spec generated by KlikAgent.\n\nTask: ${task.taskId}\nAffected paths: \`${affectedPaths}\``,
  );

  log('INFO', `[generateQaSpecFlow] Done — PR opened: ${prUrl}`);
  dashboardBus.emitEvent('github', 'info', `PR opened: ${prUrl}`, { prUrl });

  // Notify trigger service via callbackUrl so it can comment on the originating ticket
  if (task.callbackUrl) {
    const taskResult: TaskResult = {
      taskId: task.taskId,
      passed: !result.warned,
      summary: result.warned
        ? `Spec generated with warnings — may need manual review. PR: ${prUrl}`
        : `Spec generated successfully. PR: ${prUrl}`,
      reportUrl: prUrl,
      metadata: {
        tokenUsage,
        warned: result.warned,
        warningMessage: result.warningMessage,
      },
    };
    await postCallback(task.callbackUrl, taskResult);
  }
}

async function postCallback(url: string, result: TaskResult): Promise<void> {
  const maxAttempts = 3;
  const delayMs = 2000;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      const res = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(result),
      });
      if (!res.ok) {
        log('WARN', `[generateQaSpecFlow] Callback to ${url} returned ${res.status} (attempt ${attempt}/${maxAttempts})`);
      } else {
        log('INFO', `[generateQaSpecFlow] Callback posted to ${url}`);
        return;
      }
    } catch (err) {
      log('WARN', `[generateQaSpecFlow] Callback to ${url} failed: ${(err as Error).message} (attempt ${attempt}/${maxAttempts})`);
    }
    if (attempt < maxAttempts) await new Promise((r) => setTimeout(r, delayMs));
  }
  log('WARN', `[generateQaSpecFlow] Callback to ${url} gave up after ${maxAttempts} attempts`);
}
