import { TriggerContext } from '../types';
import { log } from '../utils/logger';
import { getIssue, commentOnIssue, transitionToInQA } from '../services/issues';
import { getKeywordMap } from '../services/testRepo';
import { detectFeature } from '../utils/featureDetector';
import { fetchPRDiff } from '../utils/diffAnalyzer';
import { resolveStartingUrls } from '../utils/pagesResolver';
import { parsePersonasFromIssue } from '../services/personas';
import { runWithSelfCorrection } from '../services/selfCorrection';
import {
  findPRByTicketId,
  getDefaultBranchSha,
  createBranch,
  openPR,
  commitFile,
  testRepoName,
  ownerName,
  mainRepo,
} from '../services/github';
import { toSpecFileName, toBranchSlug } from '../utils/naming';
import { pomPathFromContent } from '../agents/tools/outputTools';

export async function generateQaSpecFlow(context: TriggerContext): Promise<void> {
  log('INFO', `[generateQaSpecFlow] Starting for issue #${context.ticketId}`);

  // Step 1: Fetch issue
  const issue = await getIssue(Number(context.ticketId));

  // Step 2: Detect feature
  const keywordMap = await getKeywordMap().catch(() => ({} as Record<string, string[]>));
  const feature = detectFeature(issue.body, issue.labels, issue.title, keywordMap);
  log('INFO', `[generateQaSpecFlow] Feature detected: ${feature}`);

  // Step 3: Parse personas from issue body
  const personas = parsePersonasFromIssue(issue.body);
  log('INFO', `[generateQaSpecFlow] Personas from issue: [${personas.join(', ')}]`);

  // Step 4: Resolve starting URLs
  const startingUrls = await resolveStartingUrls(feature, issue.body).catch((err: Error) => {
    log('WARN', `[generateQaSpecFlow] resolveStartingUrls failed — ${err.message}. Falling back to empty array.`);
    return [] as string[];
  });
  log('INFO', `[generateQaSpecFlow] Starting URLs (${startingUrls.length}): ${startingUrls.join(', ')}`);

  // Step 5: Fetch PR diff from dev repo (best-effort)
  let prDiff = '';
  const devPR = await findPRByTicketId(context.ticketId, mainRepo()).catch(() => null);
  if (devPR) {
    prDiff = await fetchPRDiff(devPR.number, ownerName(), mainRepo(), process.env.GITHUB_TOKEN ?? '');
    log('INFO', `[generateQaSpecFlow] PR diff fetched (${prDiff.length} chars)`);
  }

  // Step 6: Create QA branch
  const branch = toBranchSlug(context.ticketId, issue.title);
  const baseSha = await getDefaultBranchSha(testRepoName());
  await createBranch(testRepoName(), branch, baseSha);
  log('INFO', `[generateQaSpecFlow] QA branch created: ${branch}`);

  // Step 7: Derive spec path
  const specPath = `tests/web/${feature}/${toSpecFileName(context.ticketId, issue.title)}`;
  log('INFO', `[generateQaSpecFlow] Spec path: ${specPath}`);

  // Step 8: Run self-correction loop (QA agent + validation)
  const result = await runWithSelfCorrection(
    issue,
    feature,
    branch,
    personas,
    startingUrls,
    prDiff,
    specPath,
  );

  let specContent = result.specContent;
  let pomContent = result.pomContent;
  let pomPath = result.pomPath;
  const affectedPaths = result.affectedPaths;
  const tokenUsage = result.tokenUsage;

  // Step 9: Sanity-check pomPath via pomPathFromContent
  const derivedPath = pomPathFromContent(pomContent, feature);
  if (pomPath !== derivedPath) {
    log('WARN', `[generateQaSpecFlow] pomPath mismatch — agent said "${pomPath}", class name implies "${derivedPath}". Using derived path.`);
    pomPath = derivedPath;
  }

  // Step 10: Commit spec + POM to branch
  await commitFile(
    testRepoName(), branch, specPath, specContent,
    `feat(spec): add #${context.ticketId} spec [klikagent]`,
  );
  await commitFile(
    testRepoName(), branch, pomPath, pomContent,
    `feat(pom): add ${feature} POM for #${context.ticketId} [klikagent]`,
  );

  // Step 11: Open PR in klikagent-tests
  const prUrl = await openPR(
    testRepoName(),
    branch,
    `[QA] #${context.ticketId} ${issue.title}`,
    `Automated test spec generated by KlikAgent.\n\nIssue: ${issue.url}\nFeature: \`${feature}\`\nAffected paths: \`${affectedPaths}\``,
  );

  // Step 12: Transition issue label
  await transitionToInQA(Number(context.ticketId));

  // Step 13: Comment on issue
  const warnBlock = result.warned
    ? `\n\n> ⚠️ **Warning:** ${result.warningMessage ?? 'Self-correction exhausted all attempts — spec may need manual review.'}`
    : '';

  await commentOnIssue(
    Number(context.ticketId),
    `🤖 **KlikAgent** — QA spec generated!\n\n` +
    `PR: ${prUrl}\n\n` +
    `URLs crawled: ${startingUrls.length}\n\n` +
    `Issue moved to \`status:in-qa\`. Tests will run automatically on the PR.\n\n` +
    `> Tokens: ${tokenUsage.promptTokens.toLocaleString()} prompt + ${tokenUsage.completionTokens.toLocaleString()} completion = **${tokenUsage.totalTokens.toLocaleString()} total**` +
    warnBlock,
  );

  log('INFO', `[generateQaSpecFlow] Done — PR opened: ${prUrl}`);
}
